Update postinst
Try:
- not to use switch case

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -24,25 +24,55 @@ else
 fi
 # Check and start tor / privoxy service should be stopped.
 # Check tor / privoxy systemd setting.
-torResponse="$(systemctl status tor 2>&1)"
-case $torResponse in
-*disabled*)
+torResponse=$(systemctl status tor 2>&1)
+if [ "$torResponse#*disabled" != "$torResponse" ]; then
     systemctl enable tor || echo "Failed to enable tor" >&2
     systemctl stop tor || echo "Failed to stop tor" >&2
-    ;;
-*running*)
-    systemctl stop tor
-    ;;
-*dead*)
+elif [ "$torResponse#*running" != "$torResponse" ]; then
+    systemctl stop tor || echo "Failed to stop tor" >&2
+elif [ "$torResponse#*dead" != "$torResponse" ]; then
     echo "Tor already stopped."
-    ;;
-*)
+else
     echo "Unknown tor program status! Response:"
     #print what is wrong.
     echo "$torResponse"
     exit 1
-    ;;
-esac
+fi
+# stateCounter=0
+# while true; do
+#     torResponse=$(systemctl status tor 2>&1)
+#     case $torResponse in
+#     *waiting*)
+#         if [ $stateCounter -ge 60 ]; then
+#             echo "tor failed to start within 60 seconds, exiting."
+#             exit 1
+#         fi
+#         echo "Waiting for tor..."
+#         sleep 1
+#         stateCounter=$(($stateCounter + 1))
+#         continue
+#         ;;
+#     *disabled*)
+#         systemctl enable tor || echo "Failed to enable tor" >&2
+#         systemctl stop tor || echo "Failed to stop tor" >&2
+#         break
+#         ;;
+#     *running*)
+#         systemctl stop tor || echo "Failed to stop tor" >&2
+#         break
+#         ;;
+#     *dead*)
+#         echo "Tor already stopped."
+#         break
+#         ;;
+#     *)
+#         echo "Unknown tor program status! Response:"
+#         #print what is wrong.
+#         echo "$torResponse"
+#         exit 1
+#         ;;
+#     esac
+# done
 while true; do
     privoxyResponse=$(systemctl status privoxy 2>&1)
     case "$privoxyResponse" in
@@ -92,4 +122,3 @@ rm -rf /usr/src/torcontroller/tmp
 echo "postinst script finished."
 
 #DEBHELPLER#
-exit 0
